### ISSUE TITLE
Delete uploaded image

### ISSUE THREAD

**Issue by stoufax** [quru/qis#35]
Hi, How it is possible to delete images via the rest api after they re uploaded by `api/v1/upload` endpoint ?

**Comment by qururoland** [comment]
Hi Mustafa,

The filesystem api is used to move, rename or delete any files after you have used upload to put a new file in place. Details of this can be found at [https://github.com/quru/qis/blob/master/doc/api_help.md#api_disk_files](https://github.com/quru/qis/blob/master/doc/api_help.md#api_disk_files) and will look something like `api/v1/admin/filesystem/images/141/`

Hope that helps!
